######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 1 21:24:40 2008
######################################################################

QT += testlib network
CONFIG -= app_bundle
TEMPLATE = app
TARGET = 
DEPENDPATH += . ..
INCLUDEPATH += . .. /opt/local/include/xmms2
LIBS += -lxmms2qt
LIBPATH += ..

# workaround broken qmake
LIBS += -lQtTest
QMAKE_LFLAGS += -Wl,-rpath,..


CONFIG += link_pkgconfig
PKGCONFIG += xmms2-plugin


# Input
HEADERS += testBasics.h

SOURCES += main.cpp \
           testBasics.cpp
